## ** test script generated by Gemini, run with caution
# might need to move text_extractor file
import os
from text_extractor import extract_text
import logging

logging.basicConfig(level=logging.INFO)

# --- Configure test files ---
test_dir = "test_files/" # IMPORTANT: Set this path correctly
test_files = [
    "eor-f2024.txt",
    "sample.pdf",
    "empty.txt"
    # add a .docx and some unsupported type to test
]

for filename in test_files:
    filepath = os.path.join(test_dir, filename)
    print(f"\n--- Testing: {filepath} ---")
    if os.path.exists(filepath):
        extracted = extract_text(filepath)
        if extracted:
            print(f"Extracted Text (first 200 chars): {extracted[:200]}...")
            print(f"Total length: {len(extracted)}")
        elif extracted == "": # Handle empty files explicitly if needed
             print("Extracted empty string (likely an empty file).")
        else: # Function returned None (error or unsupported)
             print("Extraction returned None (error or unsupported type).")
    else:
        print("File not found.")